resilience4j:
  ratelimiter:
    instances:
      checkoutLimiter:
        limitForPeriod: 20
        limitRefreshPeriod: 1m
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100

management:
  health:
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always