version: '3.8'

services:
  flask1:
    build: ./flask
    container_name: flask1
    networks:
      - loadbalance-net

  flask2:
    build: ./flask
    container_name: flask2
    networks:
      - loadbalance-net

  nginx:
    build: ./nginx
    container_name: nginx-loadbalancer
    ports:
      - "8081:8080"
    depends_on:
      - flask1
      - flask2
    networks:
      - loadbalance-net

networks:
  loadbalance-net:
    driver: bridge